# This is a basic workflow to help you get started with Actions

name: CI
on: [push]

env:
  PROJECT: demo-action
  APP_NAME: myapp
  RUNNER_OS: linux

jobs:
  build:
    name: Setup and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Maven
      run: |
        cd ${GITHUB_WORKSPACE}
        mvn package
    - name: Lucas Test Build Action
      uses: lstocchi/buildah-action@0.0.3
      with:
        new-image-name: test2
        base-image: docker.io/fabric8/java-alpine-openjdk11-jre
        content: ${GITHUB_WORKSPACE}/target/spring-petclinic-2.3.0.BUILD-SNAPSHOT.jar
        port: 8080
        entrypoint: java    
    - name: Check image created
      run: |
        buildah images

    
