name: Create Archive
on:
  push:
    tags:
       - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release.zip'
        exclusions: '*.git* .travis.yml'
    - name: Github Release create, update, and upload assets
      uses: meeDamian/github-release@v2.0.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: 'release.zip'
